### ISSUE TITLE
Review wptagent install steps/config - particularly for Firefox

### ISSUE THREAD

**Issue by stephendonner** [mozilla-services/webpagetest-settings#6]
We should take care, @jbuck, to review these ```wptagent``` install/config tips:

https://github.com/WPO-Foundation/wptagent/blob/master/docs/install.md#os-notes

@soulgalore - has Wikimedia also made these (and potentially other?) tweaks?

**Comment by jbuck** [comment]
If these are specific to the driver, I don't know how easily I can change these - I'm using the AMIs direct from https://github.com/WPO-Foundation/webpagetest-docs/blob/master/user/Private%20Instances/ec2_agents.md#ami-images
